apiVersion: v1
kind: Pod
metadata:
  name: tester
spec:
  restartPolicy: OnFailure
  containers:
  - name: ytentry
    image: local:current
    env:
    - name: YT_CONFIG_PATCHES
      value: '{proxy={enable_proxy_discovery=%false}}'
    - name: YT_TOKEN
      value: 'password'
    command: ['yt', '--proxy', "$(HTTP_PROXIES_LB_SERVICE_HOST):$(HTTP_PROXIES_LB_SERVICE_PORT)", 'list', '/']
